
import { BusinessUnit, Product } from './types';

export const COLORS = {
  [BusinessUnit.DHABA]: 'bg-orange-600',
  [BusinessUnit.BAR]: 'bg-slate-900',
  [BusinessUnit.ROOMS]: 'bg-purple-700',
  [BusinessUnit.SNOOKER]: 'bg-emerald-700',
  [BusinessUnit.ADMIN]: 'bg-gray-800',
};

export const TEXT_COLORS = {
  [BusinessUnit.DHABA]: 'text-orange-600',
  [BusinessUnit.BAR]: 'text-slate-900',
  [BusinessUnit.ROOMS]: 'text-purple-700',
  [BusinessUnit.SNOOKER]: 'text-emerald-700',
  [BusinessUnit.ADMIN]: 'text-gray-800',
};

export const SAMPLE_MENU: Product[] = [
  // --- STARTERS & SNACKS ---
  { id: '1', name: 'Paneer Tikka', localName: 'पनीर टिक्का', price: 280, image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=500&auto=format&fit=crop&q=60', category: 'food', subCategory: 'Starters', bu: BusinessUnit.DHABA, isVeg: true, isAvailable: true, isRecommended: true },
  { id: '2', name: 'Chicken Tikka', localName: 'चिकन टिक्का', price: 320, image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=500&auto=format&fit=crop&q=60', category: 'food', subCategory: 'Starters', bu: BusinessUnit.DHABA, isVeg: false, isAvailable: true },
  { id: '3', name: 'Veg Seekh Kebab', localName: 'वेज सीख कबाब', price: 240, image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=60', category: 'food', subCategory: 'Starters', bu: BusinessUnit.DHABA, isVeg: true, isAvailable: true },
  { id: '4', name: 'Tandoori Chicken', localName: 'तंदूरी चिकन', price: 450, image: 'https://images.unsplash.com/photo-1628294895950-98052523e036?w=500&auto=format&fit=crop&q=60', category: 'food', subCategory: 'Starters', bu: BusinessUnit.DHABA, isVeg: false, isAvailable: true, isRecommended: true },
  
  // --- MAIN COURSE (VEG) ---
  { id: '5', name: 'Dal Makhani', localName: 'दाल मखनी', price: 260, image: 'https://images.unsplash.com/photo-1546833999-b9f5816029bd?w=500&auto=format&fit=crop&q=60', category: 'food', subCategory: 'Main Course', bu: BusinessUnit.DHABA, isVeg: true, isAvailable: true, isRecommended: true },
  { id: '6', name: 'Paneer Butter Masala', localName: 'पनीर बटर मसाला', price: 310, image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500&auto=format&fit=crop&q=60', category: 'food', subCategory: 'Main Course', bu: BusinessUnit.DHABA, isVeg: true, isAvailable: true },
  { id: '7', name: 'Shahi Paneer', localName: 'शाही पनीर', price: 320, image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=500&auto=format&fit=crop&q=60', category: 'food', subCategory: 'Main Course', bu: BusinessUnit.DHABA, isVeg: true, isAvailable: true },
  { id: '8', name: 'Mix Veg', localName: 'मिक्स वेज', price: 220, image: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=500&auto=format&fit=crop&q=60', category: 'food', subCategory: 'Main Course', bu: BusinessUnit.DHABA, isVeg: true, isAvailable: true },
  { id: '9', name: 'Aloo Gobi', localName: 'आलू गोभी', price: 190, image: 'https://images.unsplash.com/photo-1626500155611-2092a7f53dfb?w=500&auto=format&fit=crop&q=60', category: 'food', subCategory: 'Main Course', bu: BusinessUnit.DHABA, isVeg: true, isAvailable: true },
  { id: '10', name: 'Chana Masala', localName: 'चना मसाला', price: 210, image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=500&auto=format&fit=crop&q=60', category: 'food', subCategory: 'Main Course', bu: BusinessUnit.DHABA, isVeg: true, isAvailable: true },
  { id: '11', name: 'Yellow Dal Tadka', localName: 'पीली दाल तड़का', price: 180, image: 'https://images.unsplash.com/photo-1626500155708-5953047bb72a?w=500&auto=format&fit=crop&q=60', category: 'food', subCategory: 'Main Course', bu: BusinessUnit.DHABA, isVeg: true, isAvailable: true },

  // --- MAIN COURSE (NON-VEG) ---
  { id: '12', name: 'Butter Chicken', localName: 'बटर चिकन', price: 450, image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=500&auto=format&fit=crop&q=60', category: 'food', subCategory: 'Main Course', bu: BusinessUnit.DHABA, isVeg: false, isAvailable: true, isRecommended: true },
  { id: '13', name: 'Chicken Curry', localName: 'चिकन करी', price: 380, image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=500&auto=format&fit=crop&q=60', category: 'food', subCategory: 'Main Course', bu: BusinessUnit.DHABA, isVeg: false, isAvailable: true },
  { id: '14', name: 'Mutton Rogan Josh', localName: 'मटन रोगन जोश', price: 550, image: 'https://images.unsplash.com/photo-1585937421612-70a008356f36?w=500&auto=format&fit=crop&q=60', category: 'food', subCategory: 'Main Course', bu: BusinessUnit.DHABA, isVeg: false, isAvailable: true },
  { id: '15', name: 'Egg Curry', localName: 'अंडा करी', price: 250, image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=500&auto=format&fit=crop&q=60', category: 'food', subCategory: 'Main Course', bu: BusinessUnit.DHABA, isVeg: false, isAvailable: true },
  { id: '16', name: 'Chicken Biryani', localName: 'चिकन बिरयानी', price: 350, image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&auto=format&fit=crop&q=60', category: 'food', subCategory: 'Rice & Biryani', bu: BusinessUnit.DHABA, isVeg: false, isAvailable: true, isRecommended: true },

  // --- BREADS & RICE ---
  { id: '17', name: 'Tandoori Roti', localName: 'तंदूरी रोटी', price: 20, image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?w=500&auto=format&fit=crop&q=60', category: 'food', subCategory: 'Breads', bu: BusinessUnit.DHABA, isVeg: true, isAvailable: true },
  { id: '18', name: 'Butter Naan', localName: 'बटर नान', price: 50, image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?w=500&auto=format&fit=crop&q=60', category: 'food', subCategory: 'Breads', bu: BusinessUnit.DHABA, isVeg: true, isAvailable: true, isRecommended: true },
  { id: '19', name: 'Garlic Naan', localName: 'गार्लिक नान', price: 70, image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?w=500&auto=format&fit=crop&q=60', category: 'food', subCategory: 'Breads', bu: BusinessUnit.DHABA, isVeg: true, isAvailable: true },
  { id: '20', name: 'Jeera Rice', localName: 'जीरा राइस', price: 150, image: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=500&auto=format&fit=crop&q=60', category: 'food', subCategory: 'Rice & Biryani', bu: BusinessUnit.DHABA, isVeg: true, isAvailable: true },

  // --- BAR MENU ---
  { id: '21', name: 'Royal Stag', localName: 'रॉयल स्टैग', price: 180, image: 'https://images.unsplash.com/photo-1606757367839-470213d27457?w=500', category: 'drink', subCategory: 'Whisky', bu: BusinessUnit.BAR, isVeg: true, isAvailable: true, stock: 12 },
  { id: '23', name: 'Blenders Pride', localName: 'ब्लेंडर्स प्राइड', price: 220, image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=500', category: 'drink', subCategory: 'Whisky', bu: BusinessUnit.BAR, isVeg: true, isAvailable: true, stock: 8 },
  { id: '24', name: 'Black Dog', localName: 'ब्लैक डॉग', price: 350, image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500', category: 'drink', subCategory: 'Whisky', bu: BusinessUnit.BAR, isVeg: true, isAvailable: true, stock: 5 },
  { id: '25', name: 'Old Monk', localName: 'ओल्ड मोंक', price: 150, image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=500', category: 'drink', subCategory: 'Rum', bu: BusinessUnit.BAR, isVeg: true, isAvailable: true, stock: 20 },
  { id: '26', name: 'Kingfisher Ultra', localName: 'किंगफिशर', price: 250, image: 'https://images.unsplash.com/photo-1625126596395-8c01e5140136?w=500', category: 'drink', subCategory: 'Beer', bu: BusinessUnit.BAR, isVeg: true, isAvailable: true, stock: 48 },
  { id: '27', name: 'Corona', localName: 'कोरोना', price: 350, image: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=500', category: 'drink', subCategory: 'Beer', bu: BusinessUnit.BAR, isVeg: true, isAvailable: true, stock: 24 },
  
  // -- NEW LIQUOR ITEMS --
  { id: '28', name: 'Jack Daniels', localName: 'जैक डेनियल्स', price: 500, image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500', category: 'drink', subCategory: 'Whisky', bu: BusinessUnit.BAR, isAvailable: true, stock: 10 },
  { id: '29', name: 'Chivas Regal 12', localName: 'शिवास रीगल', price: 550, image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=500', category: 'drink', subCategory: 'Whisky', bu: BusinessUnit.BAR, isAvailable: true, stock: 6 },
  { id: '30', name: 'Jameson', localName: 'जेमसन', price: 400, image: 'https://images.unsplash.com/photo-1606757367839-470213d27457?w=500', category: 'drink', subCategory: 'Whisky', bu: BusinessUnit.BAR, isAvailable: true, stock: 15 },
  { id: '31', name: 'Teachers Highland', localName: 'टीचर्स', price: 280, image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=500', category: 'drink', subCategory: 'Whisky', bu: BusinessUnit.BAR, isAvailable: true, stock: 18 },
  { id: '32', name: '100 Pipers', localName: '100 पाइपर्स', price: 250, image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500', category: 'drink', subCategory: 'Whisky', bu: BusinessUnit.BAR, isAvailable: true, stock: 22 },
  { id: '33', name: 'Antiquity Blue', localName: 'एंटीक्विटी', price: 260, image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=500', category: 'drink', subCategory: 'Whisky', bu: BusinessUnit.BAR, isAvailable: true, stock: 14 },
  { id: '34', name: 'Signature', localName: 'सिग्नेचर', price: 200, image: 'https://images.unsplash.com/photo-1606757367839-470213d27457?w=500', category: 'drink', subCategory: 'Whisky', bu: BusinessUnit.BAR, isAvailable: true, stock: 16 },
  { id: '35', name: 'Absolut Vodka', localName: 'एब्सोल्यूट वोदका', price: 350, image: 'https://images.unsplash.com/photo-1616428751070-07f0f622416f?w=500', category: 'drink', subCategory: 'Vodka', bu: BusinessUnit.BAR, isAvailable: true, stock: 9 },
  { id: '36', name: 'Smirnoff', localName: 'स्मिरनोफ', price: 220, image: 'https://images.unsplash.com/photo-1616428751070-07f0f622416f?w=500', category: 'drink', subCategory: 'Vodka', bu: BusinessUnit.BAR, isAvailable: true, stock: 25 },
  { id: '37', name: 'Magic Moments', localName: 'मैजिक मोमेंट्स', price: 180, image: 'https://images.unsplash.com/photo-1616428751070-07f0f622416f?w=500', category: 'drink', subCategory: 'Vodka', bu: BusinessUnit.BAR, isAvailable: true, stock: 30 },
  { id: '38', name: 'Bacardi White', localName: 'बकार्डी', price: 240, image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=500', category: 'drink', subCategory: 'Rum', bu: BusinessUnit.BAR, isAvailable: true, stock: 12 },
  { id: '39', name: 'Captain Morgan', localName: 'कैप्टन मॉर्गन', price: 230, image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=500', category: 'drink', subCategory: 'Rum', bu: BusinessUnit.BAR, isAvailable: true, stock: 10 },
  
  // --- OTHERS ---
  { id: '22', name: 'Snooker Table (1 Hr)', localName: 'स्नूकर (१ घंटा)', price: 200, image: 'https://images.unsplash.com/photo-1585869272332-901a1d13f563?w=500', category: 'snooker', bu: BusinessUnit.SNOOKER, isVeg: true, isAvailable: true },

  // --- ROOMS ---
  { id: '101', name: '101', localName: '१०१', price: 2000, image: 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=500', category: 'room', bu: BusinessUnit.ROOMS, isAvailable: true },
  { id: '102', name: '102', localName: '१०२', price: 2000, image: 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=500', category: 'room', bu: BusinessUnit.ROOMS, isAvailable: false },
  { id: '103', name: '103', localName: '१०३', price: 2000, image: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=500', category: 'room', bu: BusinessUnit.ROOMS, isAvailable: true },
  { id: '104', name: '104', localName: '१०४', price: 2000, image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=500', category: 'room', bu: BusinessUnit.ROOMS, isAvailable: true },
  { id: '105', name: '105', localName: '१०५', price: 2500, image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=500', category: 'room', bu: BusinessUnit.ROOMS, isAvailable: true },
  { id: '201', name: '201', localName: '२०१', price: 3000, image: 'https://images.unsplash.com/photo-1591088398332-8a7791972843?w=500', category: 'room', bu: BusinessUnit.ROOMS, isAvailable: false },

];

export const UI_TEXT = {
  en: {
    login: "Login",
    scanQr: "Scan QR",
    orderFood: "Order Food",
    seeRooms: "See Rooms",
    playSnooker: "Snooker & Play",
    barAdults: "Bar (Adults)",
    items: "Items",
    add: "Add",
    total: "Total",
    confirm: "Confirm",
    kitchen: "Kitchen KDS",
    ready: "Mark Done",
    waiter: "Waiter POS",
    settlement: "Shift Settlement",
    onboarding: "Staff Onboarding",
    sayOrder: "Tap to Speak Order",
    listening: "Listening...",
    processing: "Thinking...",
    // Manage
    manage: "Manage",
    manageOrders: "Manage Orders",
    manageMenu: "Manage Menu",
    createItem: "Create New Item",
    itemName: "Item Name",
    localName: "Hindi Name",
    price: "Price",
    image: "Image URL",
    available: "Available",
    outOfStock: "Out of Stock",
    veg: "Veg",
    nonVeg: "Non-Veg",
    save: "Save Item",
    orderSuccess: "Order Successful!",
    orderSuccessMsg: "Your order has been sent to the kitchen.",
    incoming: "Incoming",
    preparing: "Preparing",
    pickedUp: "Picked Up",
    cancel: "Cancel",
    accept: "Accept",
    markReady: "Mark Ready",
    markPicked: "Mark Picked Up",
    checkout: "Checkout",
    subtotal: "Subtotal",
    tax: "Taxes",
    grandTotal: "Grand Total",
    mostOrdered: "Most Ordered",
    searchPlaceholder: "Search dishes...",
    // Inventory
    inventory: "Inventory",
    mainInventory: "Main Inventory (Raw)",
    kitchenInventory: "Kitchen Inventory",
    stockLevel: "Current Stock",
    lowStock: "Low Stock",
    update: "Update",
  },
  hi: {
    login: "लॉग इन",
    scanQr: "स्कैन करें",
    orderFood: "खाना मंगवाएं",
    seeRooms: "कमरे देखें",
    playSnooker: "स्नूकर खेलें",
    barAdults: "बार (वयस्क)",
    items: "वस्तुएं",
    add: "जोड़ें",
    total: "कुल",
    confirm: "पुष्टि करें",
    kitchen: "रसोई",
    ready: "तैयार है",
    waiter: "वेटर",
    settlement: "हिसाब",
    onboarding: "स्टाफ जोड़ें",
    sayOrder: "बोल कर आर्डर दें",
    listening: "सुन रहा हूँ...",
    processing: "सोच रहा हूँ...",
    // Manage
    manage: "प्रबंधन",
    manageOrders: "आर्डर प्रबंधन",
    manageMenu: "मेनू प्रबंधन",
    createItem: "नया आइटम बनाएं",
    itemName: "आइटम का नाम",
    localName: "हिंदी नाम",
    price: "कीमत",
    image: "तस्वीर URL",
    available: "उपलब्ध है",
    outOfStock: "ख़त्म हो गया",
    veg: "शाकाहारी",
    nonVeg: "मांसाहारी",
    save: "सेव करें",
    orderSuccess: "आर्डर सफल!",
    orderSuccessMsg: "आपका आर्डर रसोई में भेज दिया गया है।",
    incoming: "नया आर्डर",
    preparing: "बन रहा है",
    pickedUp: "ले लिया",
    cancel: "रद्द करें",
    accept: "स्वीकार करें",
    markReady: "तैयार करें",
    markPicked: "उठा लिया",
    checkout: "चेकआउट",
    subtotal: "उप-योग",
    tax: "टैक्स",
    grandTotal: "कुल योग",
    mostOrdered: "सबसे ज्यादा पसंद",
    searchPlaceholder: "खाना खोजें...",
    // Inventory
    inventory: "भंडार (Inventory)",
    mainInventory: "कच्चा सामान (Main)",
    kitchenInventory: "रसोई भंडार (Kitchen)",
    stockLevel: "मौजूदा स्टॉक",
    lowStock: "स्टॉक कम है",
    update: "बदलें",
  }
};
