
import React from 'react';
import { 
  Utensils, 
  Bed, 
  Gamepad2, 
  Wine, 
  QrCode, 
  User, 
  Mic, 
  Volume2, 
  Plus, 
  Minus, 
  Check, 
  Clock, 
  Camera,
  X,
  LogOut,
  AlertCircle,
  Search,
  Filter,
  Trash2,
  Edit2,
  ChevronUp,
  ChevronDown,
  Settings,
  History,
  Banknote,
  CreditCard,
  Smartphone,
  CheckCircle,
  Bell,
  ArrowRight,
  BarChart3,
  TrendingUp,
  Calendar,
  Lock,
  Unlock,
  LayoutGrid,
  RefreshCw,
  Save,
  ArrowRightLeft,
  PieChart,
  Activity,
  AlertTriangle,
  Wallet,
  ChefHat
} from 'lucide-react';

export const Icons = {
  Food: Utensils,
  Room: Bed,
  Snooker: Gamepad2,
  Bar: Wine,
  QR: QrCode,
  Login: User,
  User: User,
  Mic: Mic,
  Audio: Volume2,
  Plus: Plus,
  Minus: Minus,
  Check: Check,
  Clock: Clock,
  Camera: Camera,
  Close: X,
  Logout: LogOut,
  Help: AlertCircle,
  Search: Search,
  Filter: Filter,
  Trash: Trash2,
  Edit: Edit2,
  ChevronUp: ChevronUp,
  ChevronDown: ChevronDown,
  Settings: Settings,
  History: History,
  Cash: Banknote,
  Card: CreditCard,
  Phone: Smartphone,
  CheckCircle: CheckCircle,
  Bell: Bell,
  ArrowRight: ArrowRight,
  Chart: BarChart3,
  Trending: TrendingUp,
  Calendar: Calendar,
  Lock: Lock,
  Unlock: Unlock,
  Grid: LayoutGrid,
  Transfer: ArrowRightLeft,
  Save: Save,
  Refresh: RefreshCw,
  Pie: PieChart,
  Activity: Activity,
  Warning: AlertTriangle,
  Wallet: Wallet,
  Chef: ChefHat
};
